"""Parity + behavior tests for the server-side road cross-section derivation.

The PARITY test locks the Python port byte-for-byte to the mobile TS derivation via
the shared fixture mobile/src/measurements/__fixtures__/roadCrossSectionParity.json
(generated by running the real buildRoadSectionFromInventory.ts). If the mobile
derivation changes, regenerate the fixture and both suites move together.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from app.services.road_cross_section_build import build_road_cross_section, classify_median

_FIXTURE = (
    Path(__file__).resolve().parents[2]
    / "mobile" / "src" / "measurements" / "__fixtures__" / "roadCrossSectionParity.json"
)


def _load_fixture():
    if not _FIXTURE.exists():
        pytest.skip(f"parity fixture missing: {_FIXTURE}")
    return json.loads(_FIXTURE.read_text(encoding="utf-8"))


@pytest.mark.parametrize("case", _load_fixture(), ids=lambda c: c["name"])
def test_python_matches_mobile_ts_derivation(case):
    got = build_road_cross_section(case["snapshot"], case.get("fallback"))
    assert got == case["expected"], f"parity mismatch for {case['name']}"


class TestDerivationBehavior:
    def test_no_snapshot_no_width_is_default_2_lane(self):
        cs = build_road_cross_section(None, None)
        assert cs["source"] == "DEFAULT"
        assert cs["lt_lane_count"] == 1 and cs["rt_lane_count"] == 1
        assert cs["median_category"] == "NONE" and cs["median_width_ft"] == 0

    def test_no_snapshot_with_width_is_form_fields(self):
        cs = build_road_cross_section(None, 44)
        assert cs["source"] == "FORM_FIELDS"
        assert cs["total_width_ft"] == 44
        # width split into symmetric 12 ft lanes
        assert cs["lt_lane_count"] == cs["rt_lane_count"] >= 1

    def test_snapshot_is_road_inventory(self):
        cs = build_road_cross_section({"left_lanes": 2, "right_lanes": 2, "median_type": "B", "median_width": 4}, None)
        assert cs["source"] == "ROAD_INVENTORY"
        assert cs["median_category"] == "BARRIER"
        # 4 total lanes -> freeway outside shoulders (8) and divided inside shoulders (4)
        assert cs["lt_outside_shoulder_ft"] == 8 and cs["lt_inside_shoulder_ft"] == 4

    def test_undivided_has_no_inside_shoulders(self):
        cs = build_road_cross_section({"left_lanes": 1, "right_lanes": 1, "median_type": "N"}, None)
        assert cs["lt_inside_shoulder_ft"] == 0 and cs["rt_inside_shoulder_ft"] == 0
        assert cs["median_width_ft"] == 0

    def test_median_classification(self):
        assert classify_median("R") == "RAISED"
        assert classify_median("BARRIER") == "BARRIER"
        assert classify_median("D") == "DEPRESSED"
        assert classify_median("") == "NONE"
        assert classify_median("N") == "NONE"
        assert classify_median("P") == "PAINTED"
        assert classify_median("XYZ") == "RAISED"  # unknown non-zero -> raised

    def test_optional_keys_absent_when_missing(self):
        cs = build_road_cross_section({"left_lanes": 1, "right_lanes": 1}, None)
        # PM/route/county OMITTED when absent; terrain/design_speed/adt/landmark present as null
        assert "begin_pm" not in cs and "route_name" not in cs
        assert cs["terrain_code"] is None and cs["design_speed"] is None and cs["adt"] is None
